# Generated by Django 4.2.2 on 2023-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_payment_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
