# Generated by Django 4.2.2 on 2023-07-08 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_user_role'),
        ('superUser', '0002_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='dish/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superUser.category')),
                ('food_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superUser.foodtype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.user')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
    ]
