# Generated by Django 4.2.2 on 2023-07-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superUser', '0003_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='food_type_id',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='user_id',
            new_name='user',
        ),
    ]
